yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/article.html
{% load thumbnail %}
<article>
    <ul>
      <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }} " style = "border-radius: 20px; border: 5px #ccc solid; box-shadow: 0 0 10px #444;">
    {% endthumbnail %}
    <p>{{ post.text }}</p> 
    <a class="btn btn-outline-primary" href="{% url 'posts:post_detail' post.id %}" role="button">Подробная информация</a>  
    {% if post.group %}      
    <a class="btn btn btn-outline-primary" href="{% url 'posts:group_list' post.group.slug %}" role="button">Все записи группы {{post.group}}</a>
    {% endif %} 
  </article> 

yatube/templates/includes/comment.html
{% load user_filters %}

{% if user.is_authenticated %}

<div class="card my-20">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action=" {% url 'posts:add_comment' posts.id %} ">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
<div class="media mb-4">
  <div class="media-body">
    <h5 class="mt-0">
      <a href="{% url 'posts:profile' comment.author.username %}">
        {{ comment.author.username }}
      </a>
    </h5>
    <p>
      {{ comment.text }}
    </p>
  </div>
</div>
{% endfor %}  

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/header.html
{% load static %}
<!-- Пакет JavaScript с Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"crossorigin="anonymous"></script>
    <header>  
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container-fluid">
           <a class="navbar-brand" href={% url 'posts:index' %}>
            <img src="{% static 'img/logo.png' %}" href="img/fav/fav.ico, {% url 'posts:index' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
          
          <!-- Кнопка меню -->
          <ul class="nav nav-pills">
            <div class="btn-group">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">Меню</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'about:author' %}"> Об авторе </a></li>
                <li><a class="dropdown-item" href="{% url 'about:tech' %}"> Технологии</a></li>
              </ul>
            </div>
          <!-- Кнопка меню -->

        {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
        <!--<li class="nav-item">              
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
             href="{% url 'about:author' %}"> Об авторе </a>
        </li>
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
             href="{% url 'about:tech' %}"> Технологии </a>
        </li>-->
        {% if request.user.is_authenticated %}
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" 
             href="{% url 'posts:post_create' %}"> Новая запись </a>
        </li>
        <!--<li class="nav-item">              
          <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}" 
             href="{% url 'users:password_change' %}"> Изменить пароль </a>
        </li> -->
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'posts:follow_index' %}active{% endif %}" 
             href="{% url 'posts:follow_index' %}"> Подписки </a>
        </li>
        <!-- <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" 
             href="{% url 'users:logout' %}"> Выйти </a>
        </li> -->
        
        <!-- Кнопка на логине пользователя -->
        <ul class="nav nav-pills">
          <div class="btn-group">
            <a class="btn btn dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">Пользователь: {{ user.username }}</a>
            <ul class="dropdown-menu">
              {% if request.user.is_authenticated %}
              <li><a class="dropdown-item"  href="{% url 'users:password_change' %}"> Изменить пароль</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item"  href="{% url 'users:logout' %}"> Выйти</a></li>
              {% endif %}
            </ul>
          </div>
        <!-- Кнопка на логине пользователя -->

        <!--<a class="nav-link">
            <span style="color:black"> Пользователь: {{ user.username }}</span>
        </a> -->
   
        {% else %}
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" 
             href="{% url 'users:login' %}"> Войти </a>
        </li>
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" 
             href="{% url 'users:signup' %}"> Регистрация </a>
        </li>
        {% endif %}
        </ul>
        </div>
      </nav>
    </header>   
    {% endwith %}  