yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Создание таблицы Group."""

    title = models.CharField(max_length=200, verbose_name="Название")
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name="Описание")

    class Meta:
        """Meta class."""

        verbose_name = "Группа"
        verbose_name_plural = "Группы"

    def __str__(self):
        """Получение имени сообщества."""
        return self.title[:15]


class Post(models.Model):
    """Создание таблицы Post."""

    text = models.TextField("Текст поста", help_text="Введите текст поста")
    pub_date = models.DateTimeField("Дата публикации", auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор",
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name="posts",
        blank=True,
        null=True,
        verbose_name="Группа",
        help_text="Группа, к которой будет относиться пост",
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    class Meta:
        """Meta class."""

        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["-pub_date"]

    def __str__(self):
        """Выводим текст поста."""
        return self.text[:15]


class Comment(models.Model):
    """Создание таблицы Comment."""

    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments", null=True
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comments", null=True
    )
    text = models.TextField(
        "Текст комментария", help_text="Введите текст комментария"
    )
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    """Создание таблицы Follow."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following", null=True
    )

    class Meta:
        """Meta класс."""

        verbose_name_plural = "Подписки"
        verbose_name = "Подписка"

        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"],
                name="unique_user_author",
            )
        ]

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Comment, Post

User = get_user_model()


class PostForm(forms.ModelForm):
    """Форма для Post."""

    class Meta:
        """Meta class."""

        model = Post
        fields = ("text", "group", "image")

    def clean_data(self):
        """Проверяет валидацию."""
        data = self.changed_data["text"]
        if data == "":
            raise forms.ValidationError("Поле надо заполнить")
        return data


class CommentForm(forms.ModelForm):
    """Форма для Comment."""

    class Meta:
        """Meta class."""

        model = Comment
        fields = ("text",)

    def clean_data(self):
        """Проверяет валидацию."""
        data = self.changed_data["text"]
        if data == "":
            raise forms.ValidationError("Поле надо заполнить")
        return data

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

User = get_user_model()

POST_LIMIT = 10


def paginate_posts(request, posts):
    """Паджинатор."""
    paginator = Paginator(posts, POST_LIMIT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return {
        "paginator": paginator,
        "page_number": page_number,
        "page_obj": page_obj,
    }


@cache_page(20)
def index(request):
    """Генерирует index.html."""
    template = "posts/index.html"
    posts = Post.objects.select_related("author").order_by("-pub_date")
    context = paginate_posts(request, posts)
    return render(request, template, context)


def group_posts(request, slug):
    """Генерирует group_list.html."""
    template = "posts/group_list.html"
    group = get_object_or_404(Group, slug=slug)
    context = {
        "group": group,
    }
    context.update(
        paginate_posts(request, group.posts.select_related("author"))
    )
    return render(request, template, context)


def profile(request, username):
    """Генерирует profile.html."""
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    posts_count = post_list.count()
    following = (
        request.user.is_authenticated
        and author.following.filter(user=request.user).exists()
    )
    context = {
        "author": author,
        "posts": post_list,
        "posts_count": posts_count,
        "following": following,
    }
    context.update(
        paginate_posts(
            request,
            author.posts.all().order_by("-pub_date").select_related("group"),
        )
    )
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    """Генерирует post_detail.html."""
    posts = get_object_or_404(Post, id=post_id)
    author = posts.author
    comments = posts.comments.select_related("author")
    form = CommentForm()
    posts_count = Post.objects.filter(author=author).count()
    context = {
        "posts": posts,
        "posts_count": posts_count,
        "comments": comments,
        "form": form,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    """Генерирует post_create.html."""
    if request.method == "POST":
        form = PostForm(request.POST or None, files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("posts:profile", request.user)
        return render(request, "posts/create_post.html", {"form": form})
    form = PostForm()
    return render(request, "posts/create_post.html", {"form": form})


@login_required
def post_edit(request, post_id):
    """Генерирует post_edit.html."""
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post
    )
    if request.user != post.author:
        return redirect("posts:post_detail", post.id)
    if form.is_valid():
        post = form.save()
        return redirect("posts:post_detail", post.id)
    return render(
        request,
        "posts/create_post.html",
        {"form": form, "post": post, "is_edit": is_edit},
    )


@login_required
def add_comment(request, post_id):
    """Возможность комментировать запись."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    authenticated = request.user.is_authenticated
    if authenticated:
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
        return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    """Генерирует страницу подписок."""
    follower = Follow.objects.filter(user=request.user).values_list(
        "author_id", flat=True
    )
    posts = Post.objects.filter(author_id__in=follower)
    context = paginate_posts(request, posts)
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    """Возможность подписаться."""
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:follow_index")


@login_required
def profile_unfollow(request, username):
    """Возможность отписаться."""
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect("posts:follow_index")

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{%block title%}{% if is_edit %} Редактировать {% else %} Новый пост {% endif %}{%endblock title%}
{% block content %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card" style = "border-radius: 20px; box-shadow: 0 0 10px #444;">
              <div class="card-header" >       
                
        {% if is_edit %}
          Редактировать
        {% else %}
           Новый пост
        {% endif %}    
      </div>
      <div class="card-body">
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}            
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}

        <form method="post" enctype="multipart/form-data"
        {% if is_edit %}
        action="{% url 'posts:post_edit' post.pk %}" method="post" enctype="multipart/form-data"
        {% else %}
        action= "{% url 'posts:post_create' %}"
        {% endif %}>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>    
              {{ field }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
              </button>
            </div>
          </form>
        </div> 
      </div> 
    </div> 
</div> 
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
  {%block title%}Подписки{%endblock title%}
    {% block content %}
        <h1>Подписки пользователя {{ request.user }}</h1>
        {% for post in page_obj %} 
          <article> 
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center"  upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }} " style = "border-radius: 20px; border: 5px #ccc solid; box-shadow: 0 0 10px #444;">
          {% endthumbnail %}
          <p>{{ post.text }}</p> 
          <a class="btn btn-outline-primary" href="{% url 'posts:post_detail' post.id %}" role="button">Подробная информация</a>       
          <a class="btn btn btn-outline-primary" href="{% url 'posts:profile' post.author.username %}" role="button">Все посты пользователя {{ post.author.get_full_name }}</a>
          {% if post.group %} 
          <a class="btn btn btn-outline-primary" href="{% url 'posts:group_list' post.group.slug %}" role="button">Все записи группы {{post.group}}</a>

        </article>
          {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
  {%block title%} {{ group.title }} {%endblock title%} 
    {% block content %}
        <h1>{{ group.title }}</h1>
        <p>{{ group.description }}</p>
        {% for post in page_obj %}    
          <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }} " style = "border-radius: 20px; box-shadow: 0 0 10px #444;">
            {% endthumbnail %}
          <p>{{ post.text }}</p> 
          <p><a href="{% url 'posts:profile' post.author.username %}">все посты пользователя {{ post.author.get_full_name }}</a></p> 
        </article>  
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    {% endblock %}  

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
  {%block title%}Последние обновления на сайте.{%endblock title%}
    {% block content %}
    {% include 'posts/includes/switcher.html' %}
        <h1>Последние обновления на сайте</h1>
        {% for post in page_obj %} 
          <article> 
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center"  upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }} " style = "border-radius: 20px; border: 5px #ccc solid; box-shadow: 0 0 10px #444;">
          {% endthumbnail %}
          <p>{{ post.text }}</p> 
          <a class="btn btn-outline-primary" href="{% url 'posts:post_detail' post.id %}" role="button">Подробная информация</a>       
          <a class="btn btn btn-outline-primary" href="{% url 'posts:profile' post.author.username %}" role="button">Все посты пользователя {{ post.author.get_full_name }}</a>
          {% if post.group %} 
          <a class="btn btn btn-outline-primary" href="{% url 'posts:group_list' post.group.slug %}" role="button">Все записи группы {{post.group}}</a>

        </article>
          {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}

        {% include 'posts/includes/paginator.html' %}
    {% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %} Пост {{ posts.text|truncatechars:30 }} {% endblock title %}
{% block content %}      
<div class="row">     
  <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ posts.pub_date|date:"d E Y" }}
            </li>
            {% if posts.group %}  
            <li class="list-group-item">
            Группа: {{ posts.group }}    
            <a class="btn btn-outline-primary" href="{% url 'posts:group_list' posts.group.slug %}">Все записи группы</a>
          </li>
          {% endif %}
            <li class="list-group-item">
              Автор: {{ posts.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ posts_count }}
            </li>
            <li class="list-group-item">
              <a class="d-grid gap-2" href="{% url 'posts:profile' posts.author %}">
                <button class="btn btn-primary" type="button">Все посты пользователя</button>
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail posts.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }} " style = "border-radius: 20px; box-shadow: 0 0 10px #444;">
            {% endthumbnail %}
            <p>{{ posts.text }}</p>
            {% if request.user == posts.author %}
            <a class="btn btn-outline-primary" href="{% url 'posts:post_edit' posts.id %}">
              Редактировать
            </a>     
            {% endif %}
          </article>
          {% include 'includes/comment.html' %}
      </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %} Профайл пользователя {{ author }}{% endblock title %}
{% block content %}                
  <h1>Все посты пользователя {{ author }} </h1>
    <h3>Всего постов: {{ posts_count }} </h3>
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}   
        {% for post in page_obj %}
        {% thumbnail posts.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }} " style = "border-radius: 20px; border: 5px #ccc solid; box-shadow: 0 0 10px #444;">
        {% endthumbnail %} 
        {% include 'includes/article.html' %}             
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %} 
        {% endblock %}